import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Intro from "../components/Intro";
import Navbar from "../components/Navbar";
import Services from "../components/Services";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Agency Website</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Intro />
      <Services />
    </div>
  );
}
